### ISSUE TITLE
Make airplace work with worldedit pos1 selection

### ISSUE THREAD

**Issue by Ninty9** [RedstoneTools/redstonetools-mod#132]
currently you can use airplace with the right click from the worldedit selection tool (because you're just right clicking an air block), but it would be useful to also allow the player to left click to select pos1

**Comment by orbyfied** [comment]
We could also try replacing the value Minecraft uses instead of doing the interactions ourselves, that would allow for all interactions to work in the air.

**Comment by Matthias1590** [comment]
> We could also try replacing the value Minecraft uses instead of doing the interactions ourselves, that would allow for all interactions to work in the air.
> 
> No idea how though.

what value? airplace is currently implemented by turning the crosshair raycast into a block hit if it is a miss right before an item is used, if we do this right before an item is used to left click it should add the functionality we want

**Comment by Dav321** [comment]
Could I do this?
