### ISSUE TITLE
Smart Redstone Schematic Placement

### ISSUE THREAD

**Issue by BlueFalconHD** [RedstoneTools/redstonetools-mod#207]
**Is your feature request related to a problem? Please describe.**
Building certain redstone ciruits over and over again, even if they are simple, is such a pain.

**Describe the solution you'd like**
A wand or some sort of tool allowing you to smart place schematics in an area. There would be preset schematics built in, for gates and other useful contraptions. Schematics would have indicators in them for input, output, and no-touch areas. These would help an algorithm determine the best position for the selected schematic to be placed, and this would then be previewed to the player, which they could approve with some simple control like left/right click, or move around.

**Describe alternatives you've considered**
Just using Litematica instead

**Comment by Matthias1590** [comment]
Sorry, we decided to move feature requests to the discord server instead, feel free to repost this there
