### ISSUE TITLE
More binary read and write features

### ISSUE THREAD

**Issue by DreiMu** [RedstoneTools/redstonetools-mod#215]
I had some ideas to help with binary redstone circuits, especially with the in- and outputs:
1. A way to not only read but also write into binary selections from decimal or hexadecimal
2. A way to save those selections and easily reread them or write something else
3. Maybe a way to read/write hexadecimal redstone outputs/inputs

**Comment by Matthias1590** [comment]
Sorry, we decided to move feature requests to the discord server instead, feel free to repost this there
