### ISSUE TITLE
Unexpected behaviour with Telemetry Confirmation screen and ReplayMod

### ISSUE THREAD

**Issue by BLOKBUSTR** [RedstoneTools/redstonetools-mod#245]
When I launched the game with this mod for the first time and was prompted with the Telemetry confirmation screen, the Replay Viewer button from ReplayMod appeared unexpectedly and intrusively.

Choosing an confirmation option continues to the main menu with no other issues. However, I wanted to see what would happen if I clicked the replay viewer button while still on the telemetry screen, so I deleted the redstonetools config folder containing `telemetry.json` to sorta reset the mod. Once I started the game again, I clicked on the replay viewer button. It took me to the appropriate replay viewer screen with no other issues. I clicked "Cancel" and found myself on the same telemetry confirmation screen. I was once again able to choose an option and go to the main menu.

I feel like this next bit kinda goes off-topic and isn't primarily related to this mod anymore, so I condensed it into a dropdown:

<details><summary>Off-Topic:</summary>
Next I wanted to see what would happen if I tried loading a replay, and once I did that for the first time my entire screen showed only a single color at a time with the dark vignette layered on top, and that color changed as I looked around (I also have the <a href="https://www.curseforge.com/minecraft/mc-mods/blur-fabric">Blur</a> mod, which could've possibly influenced this too). All UI elements appeared on top normally though. This single-color issue did not reoccur when I exited and returned to the replay, though. These things weren't explicitly included in the log file, but I have it attached anyway as there are still other strange things it recorded:

[2023-06-05-4.log](https://gist.github.com/BLOKBUSTR/b13491d97dfd814913d5dd44063485da)</details>

![2023-06-05_18 38 10](https://github.com/RedstoneTools/redstonetools-mod/assets/118950712/7d0a4aed-11bf-4932-b4c6-fb10fd6bc1ba)

I'm genuinely unsure whether I should've brought this issue here or to ReplayMod, as there are quite a few conflicting interactions between multiple mods not limited to these, and I can't imagine how this should be dealt with...

**Comment by Dav321** [comment]
Replaymod checks if the [CustomMainMenu Mod](https://www.curseforge.com/minecraft/mc-mods/custom-main-menu) is enabled [(here)](https://github.com/ReplayMod/ReplayMod/blob/81509a9acf712d3a36eaa375eace9499bf17daee/src/main/java/com/replaymod/replay/handler/GuiHandler.java#LL229C2-L229C2) and does not display the button if it is. In my opinion, ReplayMod should deal with this issue by adding exceptions for other Mods.

**Comment by Dav321** [comment]
Yes, their code should check if the button is allowed to display.

**Comment by JayMensink** [comment]
@Matthias1590 This can be closed, since we're planning to remove telemetry anyway (Issue #281)
