### ISSUE TITLE
Feature: Block Inventory Display

### ISSUE THREAD

**Issue by Saturn56** [RedstoneTools/redstonetools-mod#247]
Allows you to see an Inventory without clicking on it.
[Discord Post](https://discord.com/channels/1071119659346169907/1114794075686719518)

**Comment by Dav321** [comment]
These mods display the inventory of the container you are looking at:
https://www.curseforge.com/minecraft/mc-mods/jade
https://www.curseforge.com/minecraft/mc-mods/hwyla
https://curseforge.com/minecraft/mc-mods/waila
