### ISSUE TITLE
Signal strength overlay

### ISSUE THREAD

**Issue by Dav321** [RedstoneTools/redstonetools-mod#249]
On tile entitys like barrels/chests/...

Discord threads:
https://discord.com/channels/1071119659346169907/1115467856352661635
https://discord.com/channels/1071119659346169907/1114792472615342140
https://discord.com/channels/1071119659346169907/1106308865269715005

**Comment by Dav321** [comment]
Would like to do this

**Comment by Dav321** [comment]
https://discord.com/channels/1071119659346169907/1115467856352661635
https://discord.com/channels/1071119659346169907/1114792472615342140
https://discord.com/channels/1071119659346169907/1106308865269715005

**Comment by Matthias1590** [comment]
Please dont create issues for unapproved features
