### ISSUE TITLE
autodust not working

### ISSUE THREAD

**Issue by WutLolz** [RedstoneTools/redstonetools-mod#310]
i enabled autodust but when i place block theres no redstone dust above it

**Comment by WutLolz** [comment]
is there a way to make it work on iron blocks? i use it for my smaller builds

**Comment by DiamondTaco** [comment]
you should ask for help in the discord before opening an issue

**Comment by DiamondTaco** [comment]
i would recommend closing this issue and asking in one of our help channels

**Comment by WutLolz** [comment]
and uhh one more /glass isnt reggistering as a command

**Comment by DiamondTaco** [comment]
please visit this and close the issue thanks https://discord.com/channels/1071119659346169907/1105830823992762470
