### ISSUE TITLE
Server crashes on start with Fabric API and RedstoneTools

### ISSUE THREAD

**Issue by TimDev9492** [RedstoneTools/redstonetools-mod#314]
I'm using Fabric Loader 0.14.21 for minecraft 1.18.2 with Fabric API 0.76.0 and Redstone Tools 2.0.0.
Whenever I'm trying to start the server, it crashes without creating a crash report. This is the output in the console:
https://pastebin.com/5k6yMrPq

**Comment by Matthias1590** [comment]
We don't yet support servers, though we are currently working on server compatibility, if you'd like to stay up to date make sure to join our discord and keep an eye open for any announcements regarding server compatibility
