### ISSUE TITLE
Suggestion for rail pasting.

### ISSUE THREAD

**Issue by civilisedzombie** [RedstoneTools/redstonetools-mod#318]
Recently, I tried using an instant rail line instead of redstone so I could have the line instant, bi-directional, and 2 blocks per bit. I found that worldedit does not allow me to paste the rails correctly.
How they are:
![2023-11-09_10 47 16](https://github.com/RedstoneTools/redstonetools-mod/assets/76577910/89653de1-ad96-40bc-97d0-8c7b856ec176)
How they should be:
![2023-11-09_10 47 31](https://github.com/RedstoneTools/redstonetools-mod/assets/76577910/1db27f33-1a41-47dd-996b-f43fdf1a183d)
It would be good if you could fix this. I feel like this will get more attention here than on the worldedit page, though it may not be possible to fix.

**Comment by civilisedzombie** [comment]
Update: I have found a fix
Step 1: Set carpet mod rule updateSuppressionBlock to 0
Step 2: Use //reorder fast
Step 3: Avoid use of -e in pasting/stacking/fill command
Step 4: Hope you get lucky. After attempting, do a full analysis of everything. If it failed, do it again.
Step 5: ???
Step 6 Profit!
I would still like something better though.

**Comment by RUGMJ** [comment]
could you make a feature suggestion on our discord? Thanks
