### ISSUE TITLE
Update Ssb to 1.20

### ISSUE THREAD

**Issue by RUGMJ** [RedstoneTools/redstonetools-mod#331]

**Comment by Saturn56** [comment]
could someone assigne me to this?

**Comment by RUGMJ** [comment]
make sure to update any utils in a separate pr

**Comment by Saturn56** [comment]
Can I add the feature from this pr I made: https://github.com/RedstoneTools/redstonetools-mod/pull/315

**Comment by RUGMJ** [comment]
> Can I add the feature from this pr I made: #315

Lets keep all functionality the same for now so we dont overcomplicate things
