### ISSUE TITLE
Single Block Circuts and RGB Display

### ISSUE THREAD

**Issue by ChrisDev8** [RedstoneTools/redstonetools-mod#370]
# Single Block Circuts

Add multiple quality of life blocks that represent logical circuts. For example, a special repeater that has a custom size to represent a binary adder. Just like an integrated circut, where the inputs are on one side and the outputs are on another side. 

# Binary Adder Block Example
You place one corner with the block, then the other corner and the binary adder is placed. Just like the create mod. This way minecraft computers can be made much smaller and more compact, and easier to read as well.

# Additional Notes
You can add as many single block circuts representing all of the common circuts used in logical redstone.

# Analog Redstone Line
You can also add analog redstone lines that represent 8 bit or 256 signal strenghs, expanding the 4 bit limit. 

# Color Coded Redstone 
Redstone using minecraft color textures. It would be nice if different colors dont connect to other colors. Such as green redstone line will not connect to cyan redstone lines. 

# RGB Minecraft Display
This would be awesome. You use worldedit to select two positions then use //display to place a custom 8 bit RGB color display with multiple inputs and outputs. 3 8 bit inputs for rgb with support for the Analog Redstone Line as an input. 3 8 bit output that tell the user the rgb value. Then two inputs for x and y values and a reset input.

**Comment by RUGMJ** [comment]
This goes against the values of the mod, however it has previously been discussed to add features like this to a separate mod that we'd name redstone additions. I'm going to close this as it's not relevant here but if it were to ever become a thing these would be a great set of features to implement
