### ISSUE TITLE
The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by kevinski119** [RedstoneTools/redstonetools-mod#371]
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError:
An unexpected critical error was encountered

i don't really know if it's issue with mod or with my pc

crash reports:
[crash-2024-02-14_13.59.10-server.txt](https://github.com/RedstoneTools/redstonetools-mod/files/14279092/crash-2024-02-14_13.59.10-server.txt)

**Comment by Matthias1590** [comment]
We don't support forge, rst is a fabric mod

**Comment by Javatrix** [comment]
Why is it still open?
