### ISSUE TITLE
Move Functions breaking redstone

### ISSUE THREAD

**Issue by RC908** [RedstoneTools/redstonetools-mod#373]
Whenever i use my macro to move my selected build, even though my redstone is in the selection, it just breaks? And sometimes it stays but then the next move just breaks it.

**Comment by RUGMJ** [comment]
This isn't an issue with redstone tools but my guess is you forgot to add `-s` to `//move` the full command should be `//move forward -s`

**Comment by RC908** [comment]
my command is already //move 1 -s

**Comment by RC908** [comment]
i have the -s

**Comment by RC908** [comment]
i added the foward, still breaks

**Comment by RUGMJ** [comment]
Again this isn't an issue with redstone tools but with either worldedit or the commands you're running

**Comment by RC908** [comment]
but how could i fix it?

**Comment by RC908** [comment]
hmm it seems like if the redstone is on the edge of the selection, it just breaks, and as long as there is one block between it and the edge of the selection, it is mostly fine
