### ISSUE TITLE
Says install fabric, any version when i am using fabric already.

### ISSUE THREAD

**Issue by macisgreat** [RedstoneTools/redstonetools-mod#375]
Error: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Redstone Tools' (redstonetools) 1.20.4-2.0.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Os: Linux mint 21, Java 17, 
MInecraft version: 1.20.4 fabric loader version 0.15.11 Java 17

![error](https://github.com/RedstoneTools/redstonetools-mod/assets/168867159/9d3376d0-c8e2-4e42-8708-17c52e81cb8f)

**Comment by RUGMJ** [comment]
How are people unable to read.. Install fabric api

**Comment by macisgreat** [comment]
> How are people unable to read.. Install fabric api

i had it installed

**Comment by Hey-Hei** [comment]
me too (im new so i might be dum)

**Comment by spdfNerd** [comment]
This mod currently only supports minecraft 1.18.2, and you are on minecraft 1.20.4. Try downloading fabric for 1.18.2.

**Comment by Matthias1590** [comment]
You have fabric installed, not the fabric api, otherwise that message wouldnt show up. Closing this, if this hasnt been resolved yet ask for help in our discord server
