### ISSUE TITLE
fabric needed??

### ISSUE THREAD

**Issue by lusgas-dev** [RedstoneTools/redstonetools-mod#380]
![image](https://github.com/user-attachments/assets/da8dcb45-e863-4021-958d-3d95c6783c7a)

**Comment by Saturn56** [comment]
The error message means you have to install the Fabric Api for the mod to work.

**Comment by lusgas-dev** [comment]
the tab says "Fabric Loader 0.16.7", i am using fabric and it doesnt work

**Comment by Saturn56** [comment]
You have to install the Mod called Fabric API from Curseforge or Modrinth.

**Comment by lusgas-dev** [comment]
Thanks :)
